--- 
title: "Data visualization with R and ggplot2: from data to publication-quality graphics"
author: "Sarah Bonnin"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
---

# Welcome

<h3> Dates, time & location </h3>

* Dates:
  * First edition: September 27-28
	* Second edition: October 19-20

* Time:
	* 9:30-13:30 <br>

* Location:
	* IDIBAPS

<h3> Instructors </h3>
 
[Sarah Bonnin](mailto:bonninsarah@gmail.com) 

<h3>Prerequisites</h3>

The workshop is open to anyone with no (or little) prior programming experience.
Attendees must however feel comfortable enough with their own computer to install programs (and debug their installation if needed) and locate folders and files.

<h3> Learning objectives </h3>

Attendees will gain a high-level understanding of data import, manipulation and graphing with R and RStudio. They will be able to produce a variety of publication-quality graphs (among others: boxplots, histograms, dot plots, heatmaps).

<h3>Learning outcomes</h3>

* Identify and use RStudio panels (console, scripts, folders and files panels).
* Locate useful resources to learn more and know where to seek help.
* Import data from files into R.
* Manipulate and prepare (filter, select) data.
* Produce graphs:
  * Create a plot from “recipes”.
  * Change parameters (color, font size, point shape, title, etc.).
  * Export high-quality graphs in different formats (pdf, jpeg, png).

<h3>Agenda</h3>

Day 1:
* 9:30-10:00 (30’): course introduction+ check the set up.
* 10:00-10:45 (45’): introduction to R and Rstudio (Posit).
* 10:45-11:30 (45’): import data / read files.
* 11:30-12:00 (30’): break
* 12:00-12:30 (30’): ggplot2: concept and structure.
* 12:30-13:00 (30’:) guided boxplots, scatter plots, barplots, pie plots.
* 13:00-13:30 (30’): exercises / changing graph parameters.

Day 2:
* 9:30-10:00 (30’): recall what was done on day 1 with a “warm up” exercise.
* 10:00-10:45 (45’): introduction to simple data wrangling to filter and select data.
* 10:45-11:30 (45’): exercises with filtering + graphs.
* 11:30-12:00 (30’): break.
* 12:00-12:30 (30’): introduction to interactive plotting with plotly.
* 12:30-13:15 (45’): exercises combining what we learned so far.
* 13:15-13:30 (15’): workshop wrap up.